### ISSUE TITLE
TODO: Mar 1

### ISSUE THREAD

**Issue by dicook** [dicook/paper-tourrd3#1]
- [x] New GUI image
- [x] add something like this to intro: "hey, did you know you can run ANY JAVASCRIPT YOU LIKE in a Shiny application and you can pass WHATEVER YOU WANT INCLUDING JSON back and forth, this massively widens the scope of what you can do with Shiny, here's a really good example of what we did"
- [x] Put code snippet to install and run in paper
- [x] add something on D3 code, and creating the page, point to relevant code blocks
- [ ] check the handholding now
- [x] Fix rebuttal letter
